### ISSUE TITLE
Fine Tuning open model to generate textbooks

### ISSUE THREAD

**Issue by Glavin001** [SciPhi-AI/sciphi#66]

**Comment by emrgnt-cmplxty** [comment]
In order to generate the highest quality textbooks possible, we should consider fine-tuning existing open source LLMs.

The top potential candidates include:
- Mistral 7b
- CodeLLama 34b
- Llama 70b

The fine-tuning should be done on exemplar datasets, like the books located in the [Library of Phi](https://github.com/emrgnt-cmplxty/library_of_phi), paired with their respective generation prompts.

**Comment by emrgnt-cmplxty** [comment]
we are doing this now [here](https://huggingface.co/emrgnt-cmplxty/Mistral-7B-SciPhi-32k)
